"""Freeze input snapshots from xalpha, Bookmark, fin_v1 into
data/longform/<report_id>/inputs/. Also writes meta.json with handle +
display name + snapshot date so downstream stages don't have to re-read
profile.json just to render a header.

Usage:
    python3 longform/prep/freeze.py --handle aleabitoreddit
    python3 longform/prep/freeze.py --handle pelositracker --report-id pelosi
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _paths import (  # noqa: E402
    BOOKMARK_ROOT, KB_ROOT, XALPHA_ROOT,
    derive_report_id, report_inputs, report_meta_path, save_meta, validate_report_id
)


def copy_xalpha_account(handle: str, dst: Path) -> dict:
    """Copy the xalpha per-account dir. Returns {file: copied_bool}."""
    src = XALPHA_ROOT / "data" / handle
    dst.mkdir(parents=True, exist_ok=True)
    out: dict[str, bool] = {}
    for name in [
        "tweets.json", "tweets_ocr.json",
        "calls_llm.json", "calls_spark.json",
        "portfolio.json", "portfolio_charts.json",
        "dossiers.json", "signals.json", "signals_llm.json",
        "network.json", "following.json", "profile.json",
        "account_class.json",
    ]:
        s = src / name
        if s.exists():
            shutil.copy2(s, dst / name)
            out[name] = True
            print(f"  xalpha/{handle}/{name}")
        else:
            out[name] = False
    return out


def copy_xalpha_engine(dst: Path) -> None:
    dst.mkdir(parents=True, exist_ok=True)
    for name in ["portfolio_charts.py", "portfolio.py"]:
        s = XALPHA_ROOT / name
        if s.exists():
            shutil.copy2(s, dst / name)
            print(f"  xalpha_engine/{name}")


def copy_bookmark_modules(handle: str, calls_path: Path, dst: Path) -> int:
    """Copy the poster module + every ticker module that appears in this
    account's calls_llm. Cheaper than copying all 291 modules wholesale."""
    src_modules = BOOKMARK_ROOT / "data" / "modules"
    dst.mkdir(parents=True, exist_ok=True)

    poster = src_modules / f"poster_{handle}.json"
    if poster.exists():
        shutil.copy2(poster, dst / poster.name)
        print(f"  bookmark_modules/{poster.name}")

    if not calls_path.exists():
        return 0
    try:
        calls = json.loads(calls_path.read_text())
    except Exception:
        return 0
    tickers: set[str] = set()
    for c in calls:
        for ent in (c.get("tickers") or []):
            t = ent.get("ticker") if isinstance(ent, dict) else ent
            t = (t or "").strip().upper()
            if t:
                tickers.add(t)
    n_copied = 0
    for t in sorted(tickers):
        m = src_modules / f"ticker_{t.lower()}.json"
        if m.exists():
            shutil.copy2(m, dst / m.name)
            n_copied += 1
    print(f"  bookmark_modules: {n_copied}/{len(tickers)} ticker modules cached")
    return n_copied


def copy_kb_sources(dst: Path) -> int:
    src = KB_ROOT / "sources"
    dst.mkdir(parents=True, exist_ok=True)
    n = 0
    if src.exists():
        for p in src.glob("*.json"):
            shutil.copy2(p, dst / p.name)
            n += 1
    print(f"  kb_sources: {n} primary citations")
    return n


def write_meta(report_id: str, handle: str, inputs_dir: Path) -> None:
    """Pull display_name + bio from the frozen profile.json and write
    Bookmark/data/longform/<report_id>/meta.json so every downstream stage
    can look up identity strings without re-reading profile."""
    profile_path = inputs_dir / "xalpha" / handle / "profile.json"
    profile = {}
    if profile_path.exists():
        try:
            profile = json.loads(profile_path.read_text())
        except Exception:
            pass
    display_name = profile.get("display_name") or handle
    bio = profile.get("bio") or ""

    title = display_name
    subtitle = f"An explainer of @{handle}'s thesis"

    snapshot_date = datetime.now(timezone.utc).date().isoformat()

    meta = {
        "report_id": report_id,
        "handle": handle,
        "display_name": display_name,
        "bio": bio,
        "title": title,
        "subtitle": subtitle,
        "byline": (
            "Generated by Sonnet 4.6 with WebSearch + WebFetch sub-agent "
            "research, on a frozen xalpha + Bookmark + fin_v1 snapshot."
        ),
        "snapshot_date": snapshot_date,
        "frozen_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "xalpha_root": str(XALPHA_ROOT),
        "bookmark_root": str(BOOKMARK_ROOT),
        "kb_root": str(KB_ROOT),
    }
    save_meta(report_id, meta)
    print(f"\n  meta.json → {report_meta_path(report_id)}")


def report_meta_path(report_id: str):  # local re-export for the print line above
    from _paths import report_meta_path as _m
    return _m(report_id)


def freeze(handle: str, report_id: str) -> int:
    src = XALPHA_ROOT / "data" / handle
    if not src.exists():
        sys.stderr.write(
            f"error: no xalpha data for @{handle} at {src}.\n"
            f"hint: handles are case-sensitive on disk. Available handles: "
            f"`ls {XALPHA_ROOT / 'data'} | grep -i {handle}`\n"
        )
        return 2
    required = ["tweets.json", "calls_llm.json", "profile.json"]
    missing = [r for r in required if not (src / r).exists()]
    if missing:
        sys.stderr.write(
            f"error: @{handle} dir is incomplete; missing: {missing}\n"
            f"hint: run xalpha's classifier/portfolio pipeline before freezing.\n"
        )
        return 2

    inputs = report_inputs(report_id)
    inputs.mkdir(parents=True, exist_ok=True)
    print(f"Freezing inputs for @{handle} (report_id={report_id}) into {inputs}\n")

    copy_xalpha_account(handle, inputs / "xalpha" / handle)
    copy_xalpha_engine(inputs / "xalpha_engine")
    copy_bookmark_modules(
        handle,
        inputs / "xalpha" / handle / "calls_llm.json",
        inputs / "bookmark_modules",
    )
    copy_kb_sources(inputs / "kb_sources")
    write_meta(report_id, handle, inputs)
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--handle", required=True, help="X handle, e.g. aleabitoreddit")
    p.add_argument("--report-id", default=None,
                   help="Filesystem slug; defaults to derive_report_id(handle)")
    args = p.parse_args(argv)
    if getattr(args, 'report_id', None):
        validate_report_id(args.report_id)
    handle = args.handle.strip().lstrip("@")
    report_id = args.report_id or derive_report_id(handle) or handle
    return freeze(handle, report_id)


if __name__ == "__main__":
    sys.exit(main())
