"""Build chapter clusters from per-account dossiers + calls.

Reads `discover/themes.json` (the authoritative theme list, either written
by hand or generated by `discover/themes.py`) and joins it against the
account's calls_llm/dossiers to enrich each cluster with mention counts,
representative posts, dossier summaries, etc.

Output: data/longform/<report_id>/prep/themes.json — the same schema the
research stage prompt feeds on.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _paths import (  # noqa: E402
    load_meta, report_discover, report_inputs, report_prep, validate_report_id
)


def normalize(t: str) -> str:
    return (t or "").strip().lstrip("$").upper()


def load_theme_definitions(report_id: str) -> dict:
    """Read discover/themes.json. Fail loudly if missing — silently
    producing an empty themes file would let the research stage spawn
    chapters with no cluster context, which is worse than crashing."""
    p = report_discover(report_id) / "themes.json"
    if not p.exists():
        raise FileNotFoundError(
            f"missing {p}. Run discover/themes.py to generate it, or write "
            f"it by hand. Schema: {{'themes': [{{'slug','title','tickers'}}]}}."
        )
    data = json.loads(p.read_text())
    if not isinstance(data, dict) or not isinstance(data.get("themes"), list):
        raise ValueError(f"{p} has wrong shape; expected {{'themes': [...]}}")
    if not data["themes"]:
        raise ValueError(f"{p} has no themes; nothing to cluster")
    return data


def build_themes(handle: str, report_id: str, *, snapshot_date: str | None = None) -> dict:
    # Validate the theme list FIRST — otherwise a missing discover/themes.json
    # gets masked by missing-input errors below.
    theme_def = load_theme_definitions(report_id)

    in_dir = report_inputs(report_id) / "xalpha" / handle
    tweets = json.loads((in_dir / "tweets.json").read_text())
    calls = json.loads((in_dir / "calls_llm.json").read_text())
    dossiers = json.loads((in_dir / "dossiers.json").read_text())

    by_id = {str(t["id"]): t for t in tweets}

    # YTD = Jan 1 of the latest tweet's year. last_4w = snapshot - 30d.
    snapshot = snapshot_date or (
        tweets[0]["created_at"][:10] if tweets else datetime.utcnow().date().isoformat()
    )
    snap_dt = datetime.strptime(snapshot, "%Y-%m-%d")
    last_4w_start = (snap_dt - timedelta(days=30)).strftime("%Y-%m-%d")
    ytd_start = f"{snap_dt.year}-01-01"

    dossier_by_ticker = {d["ticker"]: d for d in dossiers}

    ticker_calls: dict[str, list[dict]] = defaultdict(list)
    for c in calls:
        tid = str(c.get("tweet_id"))
        tw = by_id.get(tid)
        if not tw:
            continue
        date = (tw.get("created_at") or "")[:10]
        for ent in (c.get("tickers") or []):
            t = normalize(ent.get("ticker") if isinstance(ent, dict) else ent)
            if not t:
                continue
            ticker_calls[t].append({
                "tweet_id": tid,
                "date": date,
                "row_type": c.get("row_type"),
                "is_trade_call": c.get("is_trade_call"),
                "conviction": (ent.get("conviction") if isinstance(ent, dict) else None),
                "direction": (ent.get("direction") if isinstance(ent, dict) else None),
                "action": (ent.get("action") if isinstance(ent, dict) else None),
                "text": (tw.get("text") or "")[:400],
                "url": tw.get("url") or "",
            })

    chapters: dict[str, dict] = {}

    for theme in theme_def.get("themes", []):
        slug = theme.get("slug")
        if not slug:
            continue
        title = theme.get("title", slug)
        tickers = [normalize(t) for t in (theme.get("tickers") or []) if t]

        cluster_calls: list[dict] = []
        for t in tickers:
            cluster_calls.extend(ticker_calls.get(t, []))
        cluster_calls.sort(key=lambda c: c["date"])

        per_ticker_reps: dict[str, list[dict]] = {}
        for t in tickers:
            tcalls = sorted(ticker_calls.get(t, []), key=lambda c: c["date"])
            if not tcalls:
                continue
            picks: list[dict] = []
            seen_dates: set[str] = set()
            picks.append(tcalls[0])
            seen_dates.add(tcalls[0]["date"])
            high_conv = [c for c in tcalls if c.get("conviction") == "high"]
            for c in high_conv[:2]:
                if c["date"] not in seen_dates:
                    picks.append(c); seen_dates.add(c["date"])
            recent = [c for c in tcalls if c["date"] >= last_4w_start
                      and c.get("row_type") in (
                          "thesis_or_opinion", "trade_call", "portfolio_update", "retrospective"
                      )]
            for c in recent[-3:]:
                if c["date"] not in seen_dates:
                    picks.append(c); seen_dates.add(c["date"])
            picks.sort(key=lambda c: c["date"])
            per_ticker_reps[t] = picks[:8]

        monthly = Counter(c["date"][:7] for c in cluster_calls)
        last_4w_calls = [c for c in cluster_calls if c["date"] >= last_4w_start]

        chapters[slug] = {
            "title": title,
            "tickers": tickers,
            "n_calls_total": len(cluster_calls),
            "n_calls_ytd": sum(1 for c in cluster_calls if c["date"] >= ytd_start),
            "n_calls_last_4w": len(last_4w_calls),
            "monthly_mention_counts": dict(sorted(monthly.items())),
            "per_ticker_representatives": per_ticker_reps,
            "dossier_summary": [
                {
                    "ticker": t,
                    "tier": (dossier_by_ticker.get(t) or {}).get("tier"),
                    "score": (dossier_by_ticker.get(t) or {}).get("score"),
                    "mentions": (dossier_by_ticker.get(t) or {}).get("total_mentions"),
                    "first_mention": (dossier_by_ticker.get(t) or {}).get("first_mention"),
                    "alpha": ((dossier_by_ticker.get(t) or {}).get("return") or {}).get("pct"),
                }
                for t in tickers if t in dossier_by_ticker
            ],
        }

    return {
        "windows": {
            "ytd_start": ytd_start,
            "last_4w_start": last_4w_start,
            "snapshot_date": snapshot,
        },
        "chapters": chapters,
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--handle", help="X handle; defaults to meta.json")
    p.add_argument("--report-id", required=True)
    p.add_argument("--snapshot-date", default=None)
    args = p.parse_args(argv)
    if getattr(args, 'report_id', None):
        validate_report_id(args.report_id)
    meta = load_meta(args.report_id)
    handle = (args.handle or meta.get("handle") or "").strip().lstrip("@")
    if not handle:
        p.error("could not determine handle; pass --handle or run freeze first")
    snapshot = args.snapshot_date or meta.get("snapshot_date")

    out = build_themes(handle, args.report_id, snapshot_date=snapshot)
    out_path = report_prep(args.report_id) / "themes.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False))
    print(f"→ {out_path}")
    for slug, ch in out["chapters"].items():
        print(f"  {slug:25s} tickers={len(ch['tickers']):2d} "
              f"calls={ch['n_calls_total']:4d} ytd={ch['n_calls_ytd']:3d} "
              f"last4w={ch['n_calls_last_4w']:3d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
